INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (150030, 'Cenk Alen', 'Comp. Sci.', 1.90);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (154225, 'Ahamd Firaz', 'Music', 3.10);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (154228, 'Muhammad Adil', 'Elec. Eng.', 2.10);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (154236, 'Abdul Raheem Tariq', 'History', 3.05);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (154247, 'Waqas Ahmad Sial', 'Finance', 3.21);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164031, 'Arslan Mughal', 'Physics', 1.50);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164032, 'Muhammad Talha', 'Finance', 2.10);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164036, 'Shahbaz Khan Khattak', 'Physics', 1.50);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164183, 'Stanley Ranyaradzwa', 'Biology', 3.50);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164202, 'Naimul Hasan', 'Comp. Sci.', 3.20);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164238, 'Tayyab', 'History', 2.35);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164308, 'Hamza', 'Music', 2.05);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164324, 'Ahmed Sher Malik', 'Comp. Sci.', 3.85);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164375, 'Bilal Shinwari', 'Comp. Sci.', 2.90);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164401, 'Jay Ashok Joshi', 'Biology', 3.29);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164450, 'Saad Haseeb', 'Music', 3.30);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164452, 'Luca Rinaldo Tonini', 'Comp. Sci.', 2.50);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164560, 'Waiz Ali', 'History', 2.50);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164571, 'Erica Lancaster', 'Comp. Sci.', 2.95);
INSERT INTO NewLab.student (ID, name, dept_name, tot_crd) VALUES (164685, 'Kelvin Ovuo', 'Elec. Eng.', 3.10);